apiVersion: apps/v1
kind: Deployment
metadata:
  name: dejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dejs-app
  template:
    metadata:
      labels:
        app: dejs-app
    spec:
      containers:
      - name: dejs-app
        image: jansjossy/dejs-demo-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"