apiVersion: v1
kind: Service
metadata:
  name: dejs-service
spec:
  type: NodePort
  selector:
    app: dejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30009